language: objective-c
osx_image: xcode6.4
xcode_project: DZNetworking.xcodeproj
xcode_scheme: DZNetworking
xcode_sdk: iphonesimulator8.4
before_install:
  - brew update
  - brew install carthage
  - brew install xctool
install: carthage bootstrap --verbose
script: xctool -scheme DZNetworking -project DZNetworking.xcodeproj -configuration Release -sdk iphonesimulator -arch i386 build
branches:
  only:
  - master
