language: objective-c
osx_image: xcode6.4
xcode_project: DZNetworking.xcodeproj
xcode_scheme: DZNetworking
xcode_sdk: iphonesimulator8.4
before_install:
    - brew update
    - brew install carthage
    - carthage build --no-skip-current --platform=iphonesimulator
branches:
    only:
        - master
