name: Xcode CI

on: [push]

jobs:
  test:
    name: Test 
    runs-on: macOS-latest

    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.4,name=iPhone 11 Pro']

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build and test
      run: xcodebuild clean test -scheme DZNetworking -destination "${destination}" CODE_SIGN_IDENTITY=""
      env: 
         destination: ${{ matrix.destination }}
