name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-15

    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
