name: Xcode CI

on: [push]

jobs:
  test:
    name: Test 
    runs-on: macOS-latest

    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.4.1,name=iPhone 11 Pro']

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Switch to Xcode 11
      run: sudo xcode-select -s /Applications/Xcode_11.4.1.app

    - name: Show Build Version
      run: xcodebuild -version

    - name: Show Build Settings
      run: xcodebuild -showBuildSettings
      
    - name: Show Build SDK
      run: xcodebuild -showsdks

    - name: Build and test
      run: xcodebuild clean test -scheme DZNetworking -destination "${destination}" CODE_SIGN_IDENTITY=""
      env: 
         destination: ${{ matrix.destination }}
